# Generated by Django 3.0 on 2020-12-13 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.CharField(choices=[('Actu Buzz', 'ACTU BUZZ'), ('Albums', 'ALBUMS'), ('Singles', 'SINGLES'), ('Videos', 'VIDEOS'), ('Others', 'OTHERS')], max_length=100, verbose_name='Category fields')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Slug')),
                ('content', models.TextField(blank=True, default='N/A', verbose_name='Content')),
                ('cover', models.ImageField(upload_to='articles/')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created at')),
                ('views', models.IntegerField(default=0, verbose_name='Views number')),
                ('donwload', models.IntegerField(default=0, verbose_name='Download number')),
                ('category', models.ManyToManyField(to='articles.Category')),
            ],
        ),
    ]
