# Generated by Django 3.0 on 2020-12-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articles',
            old_name='donwload',
            new_name='download',
        ),
    ]
