# Generated by Django 3.0 on 2020-12-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20201213_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='File_Uploaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to='libraries/')),
                ('type_file', models.CharField(choices=[('mp3', 'MP3'), ('mp4', 'MP4'), ('wav', 'WAV'), ('aac', 'AAC'), ('pdf', 'PDF'), ('others', 'OTHERS')], max_length=10, verbose_name='Type File')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Created At')),
            ],
        ),
        migrations.AlterField(
            model_name='articles',
            name='cover',
            field=models.ImageField(upload_to='libraries/'),
        ),
        migrations.AddField(
            model_name='articles',
            name='media',
            field=models.ManyToManyField(to='articles.File_Uploaded'),
        ),
    ]
