# Generated by Django 3.0 on 2020-12-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20201213_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='media',
            field=models.ManyToManyField(blank=True, to='articles.File_Uploaded'),
        ),
    ]
