# Generated by Django 3.0 on 2020-12-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20201217_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galleries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Title')),
                ('file', models.ImageField(upload_to='gallery/')),
                ('views', models.IntegerField(default=0, verbose_name='Views number')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
        ),
    ]
