# Generated by Django 3.0 on 2020-12-18 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20201217_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='External_Links',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Youtube', 'YOUTUBE')], max_length=30, verbose_name='Source')),
                ('link', models.URLField(max_length=255, verbose_name='Link')),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='external_link',
            field=models.ManyToManyField(blank=True, to='articles.External_Links'),
        ),
    ]
