# Generated by Django 3.0 on 2020-12-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_external_links_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='external_links',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
