# Generated by Django 3.0 on 2020-12-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20201219_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='fields',
            field=models.CharField(choices=[('Actualites', 'ACTU BUZZ'), ('Albums', 'ALBUMS'), ('Singles', 'SINGLES'), ('Videos', 'VIDEOS'), ('Others', 'OTHERS')], max_length=100, unique=True, verbose_name='Category fields'),
        ),
    ]
