# Generated by Django 3.0 on 2020-12-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_delete_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='is_in_pub',
        ),
        migrations.AddField(
            model_name='articles',
            name='slide_one',
            field=models.BooleanField(default=False, verbose_name='Slide 1'),
        ),
        migrations.AddField(
            model_name='articles',
            name='slide_three',
            field=models.BooleanField(default=False, verbose_name='Slide 3'),
        ),
        migrations.AddField(
            model_name='articles',
            name='slide_two',
            field=models.BooleanField(default=False, verbose_name='Slide 2'),
        ),
    ]
