# Generated by Django 3.0 on 2020-12-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0019_auto_20201224_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price'),
        ),
    ]
